// Character library: head frames + colours generated by scripts/build_mascots.py from
// page-mascot (MIT, see assets/mascot/LICENSE-page-mascot).
import meta from './assets/mascot/characters.json';
import type { Settings } from './shared/settings';

export type Mood = 'walk' | 'ask' | 'run' | 'sad';
/** Head frames: d0..d8 are the nine head directions (row-major, d4 = facing you); 'run' = star-struck. */
export type Frame = 'd0' | 'd1' | 'd2' | 'd3' | 'd4' | 'd5' | 'd6' | 'd7' | 'd8' | 'run';
export const FRAMES: Frame[] = ['d0', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8', 'run'];
export type TailKind = 'long' | 'curl' | 'stub' | 'puff' | 'bushy' | 'none';

// Every head frame, bundled by webpack: "./<character>/<mood>.webp" -> URL
const frames = require.context('./assets/mascot', true, /\.webp$/);
export const headSrc = (id: string, frame: Frame): string => frames(`./${id}/${frame}.webp`) as string;

const animals = meta.animals as Record<string, { body: string; belly: string; tail: TailKind; shoulder: number }>;
const humans = [...meta.humans.male, ...meta.humans.female] as { id: string; skin: string }[];

export const LABELS: Record<string, string> = {
  cat: 'Cat', dog: 'Pug', bear: 'Bear', bunny: 'Bunny', fox: 'Fox', panda: 'Panda', penguin: 'Penguin', tiger: 'Tiger',
  koala: 'Koala', raccoon: 'Raccoon', redpanda: 'Red panda', hamster: 'Hamster',
  beard: 'Beard', cap: 'Cap', bald: 'Bald', builder: 'Builder', chef: 'Chef', grandpa: 'Grandpa', sikh: 'Turban',
  wizard: 'Wizard', afro: 'Afro', ballerina: 'Bun', glasses: 'Curly', granny: 'Granny', hijabi: 'Hijab', nurse: 'Nurse',
  scientist: 'Scientist', pirate: 'Bandana', skater: 'Beanie',
};

/** Everything the figure needs to draw itself, resolved from the user's settings. */
export interface Look {
  kind: 'animal' | 'human';
  id: string;
  /** Custom (cartoonised) photo used as the face instead of the drawn head. */
  photo: string | null;
  // Animal body
  fur: string;
  belly: string;
  tail: TailKind;
  /** Width of the shoulders in the head art, in head-canvas pixels (320 wide). */
  shoulder: number;
  // Human body
  skin: string;
  outfit: Settings['outfit'];
  accessory: Settings['accessory'];
  accessoryColor: string;
}

export function resolveLook(s: Settings): Look {
  const photo = s.avatar === 'photo' ? s.photo : null;
  const animal = animals[s.animal] ?? animals.cat;
  const human = humans.find((h) => h.id === s.humanStyle) ?? humans[0];
  return {
    kind: s.character,
    id: s.character === 'animal' ? s.animal : human.id,
    photo,
    fur: animal.body,
    belly: animal.belly,
    tail: animal.tail,
    shoulder: animal.shoulder,
    skin: human.skin,
    outfit: s.outfit,
    accessory: s.accessory,
    accessoryColor: s.accessoryColor,
  };
}

/** Decode every head frame for the chosen character up front, so mood changes never flicker. */
export function preloadLook(look: Look): void {
  if (look.photo) return;
  for (const frame of FRAMES) {
    const img = new Image();
    img.src = headSrc(look.id, frame);
    img.decode?.().catch(() => undefined);
  }
}
